wandb_version: 1

output_dir:
  desc: null
  value: tmp
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: true
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
eval_strategy:
  desc: null
  value: IntervalStrategy.NO
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 2
per_device_eval_batch_size:
  desc: null
  value: 8
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 32
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 3.0e-05
weight_decay:
  desc: null
  value: 0.01
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-06
max_grad_norm:
  desc: null
  value: 5.0
num_train_epochs:
  desc: null
  value: 3.0
max_steps:
  desc: null
  value: 3000
lr_scheduler_type:
  desc: null
  value: SchedulerType.LINEAR
lr_scheduler_kwargs:
  desc: null
  value: {}
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 500
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: tmp/runs/Aug05_23-29-42_aaron-MS-7B89
logging_strategy:
  desc: null
  value: IntervalStrategy.STEPS
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: IntervalStrategy.STEPS
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: null
save_safetensors:
  desc: null
  value: true
save_on_each_node:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
restore_callback_states_from_checkpoint:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: null
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 0
dataloader_prefetch_factor:
  desc: null
  value: 2
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: tmp
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_v2: false
    xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
accelerator_config:
  desc: null
  value:
    split_batches: false
    dispatch_batches: null
    even_batches: true
    use_seedable_sampler: true
    non_blocking: false
    gradient_accumulation_kwargs: null
deepspeed:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: OptimizerNames.ADAMW_TORCH
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
dataloader_persistent_workers:
  desc: null
  value: false
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: HubStrategy.EVERY_SAVE
hub_token:
  desc: null
  value: null
hub_private_repo:
  desc: null
  value: false
hub_always_push:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: false
gradient_checkpointing_kwargs:
  desc: null
  value: null
include_inputs_for_metrics:
  desc: null
  value: false
eval_do_concat_batches:
  desc: null
  value: true
fp16_backend:
  desc: null
  value: auto
evaluation_strategy:
  desc: null
  value: null
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: null
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
dispatch_batches:
  desc: null
  value: null
split_batches:
  desc: null
  value: null
include_tokens_per_second:
  desc: null
  value: false
include_num_input_tokens_seen:
  desc: null
  value: false
neftune_noise_alpha:
  desc: null
  value: null
optim_target_modules:
  desc: null
  value: null
batch_eval_metrics:
  desc: null
  value: false
distributed_state:
  desc: null
  value: 'Distributed environment: NO

    Num processes: 1

    Process index: 0

    Local process index: 0

    Device: cpu

    '
_n_gpu:
  desc: null
  value: 0
__cached__setup_devices:
  desc: null
  value: cpu
deepspeed_plugin:
  desc: null
  value: null
val_datapath:
  desc: null
  value: ./pubmed_val.txt
train_datapath:
  desc: null
  value: ./pubmed_train.txt
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722896984.0
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.8.19
      5: 0.16.6
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
